# Generated by Django 5.1.4 on 2024-12-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_copyrighted', models.BooleanField()),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.video')),
            ],
        ),
        migrations.CreateModel(
            name='NudityDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains_nudity', models.BooleanField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoQualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_score', models.FloatField()),
                ('video_score', models.FloatField()),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='content.video')),
            ],
        ),
    ]
